# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 941bcd4cb7c3d4a3c2a03031d082d552ee4a145b3ce0e4ced07ba134173ec714fc3a9bd6b5e791239fa480eccaa71400b8df228f59bcfd37720149aea3c715ca

test:
  secret_key_base: 378d19e42c468273816bda155e8bf3dac2dd5ec48ffad0e78c956a108371763702d254ee4bea81737dc0e188094453a065141f9b6a90b11656f19b89672eb071

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
